### ISSUE TITLE
Responsive layouts for footer

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#68]
I think we could add some breaks in places when the sections start to stack up. Not sure, but maybe it's possible to reduce the large space above the "From the Blog" section as well.

![window](https://user-images.githubusercontent.com/4501388/29326284-83544216-81b0-11e7-9a5d-ed009d4427c9.png)

![window 2](https://user-images.githubusercontent.com/4501388/29326285-863185de-81b0-11e7-82dc-a0ea99bf767f.png)

**Comment by awoodruff** [comment]
Added some stuff to the 850px breakpoint:
- footer goes to single column
- "Where was that?" and "Made @ Axis" links go inline-block to reduce vertical space (but back to block for mobile because of too much line-wrapping)
- Vertical margins are generally reduced because the footer gets huge in a single column
- Reduce number of blog links to 5, for the same reason
![screen shot 2017-08-25 at 5 02 57 pm](https://user-images.githubusercontent.com/3533462/29732660-8ec2fd7c-89b7-11e7-897c-9e6edef9e630.png)
